/* #2 - The rest of the Firebase setup code goes here */
// Your web app's Firebase configuration
var firebaseConfig = {
	apiKey: "AIzaSyAajUn4yXP77CnJZFKQckx9O1NqLr0ynAo",
	authDomain: "fir-exer-f2cb4.firebaseapp.com",
	databaseURL: "https://fir-exer-f2cb4.firebaseio.com",
	projectId: "fir-exer-f2cb4",
	storageBucket: "fir-exer-f2cb4.appspot.com",
	messagingSenderId: "1084930185158",
	appId: "1:1084930185158:web:5a83f966ca3cc2a7c444c7"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);

let database = firebase.database();

let ref = database.ref('scores');


//let newScoreRef = ref.push(data);
//console.log(newScoreRef.key); // the autogenerated `key` we get back from Firebase
//console.log(newScoreRef.toString()); // the full path to that data on Firebase