 // Your web app's Firebase configuration
var firebaseConfig = {
    apiKey: "AIzaSyCac8tEBgqDcfDP-EJudTEc_rs6ZrxeTaY",
    authDomain: "project-2-b33d8.firebaseapp.com",
    databaseURL: "https://project-2-b33d8.firebaseio.com",
    projectId: "project-2-b33d8",
    storageBucket: "project-2-b33d8.appspot.com",
    messagingSenderId: "862112219142",
    appId: "1:862112219142:web:e764ca02cda76546e8c387"
};
// Initialize Firebase
firebase.initializeApp(firebaseConfig);

let database = firebase.database();

let ref = database.ref('scores');


//let newScoreRef = ref.push(data);
//console.log(newScoreRef.key); // the autogenerated `key` we get back from Firebase
//console.log(newScoreRef.toString()); // the full path to that data on Firebase